kind: ReplicationController
apiVersion: v1
metadata:
  name: etcd
  creationTimestamp: 
spec:
  strategy:
    type: Recreate
    resources: {}
  triggers:
  - type: ConfigChange
  replicas: 3
  selector:
    name: etcd
  template:
    metadata:
      creationTimestamp: 
      labels:
        name: etcd
    spec:
      containers:
      - name: member
        image: openshift/etcd-20-centos7
        ports:
        - containerPort: 2379
          protocol: TCP
        - containerPort: 2380
          protocol: TCP
        env:
        - name: ETCD_NUM_MEMBERS
          value: '3'
        - name: ETCD_INITIAL_CLUSTER_STATE
          value: new
        - name: ETCD_INITIAL_CLUSTER_TOKEN
          value: etcd-cluster-hd84j
        - name: ETCD_DISCOVERY
          value: http://etcd-discovery:2379/v2/keys/discovery/upay9zdbi9wy9y6bkfokn0w4n506c9gb9880qbvr
        resources: {}
        terminationMessagePath: "/dev/termination-log"
        imagePullPolicy: IfNotPresent
        capabilities: {}
        securityContext:
          capabilities: {}
          privileged: false
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      serviceAccount: ''
status: {}
